# Generated by Django 4.2.10 on 2024-02-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'standard'), ('D', 'Deluxe'), ('SU', 'suite'), ('DD', 'Double Deluxe')], default='S', max_length=2)),
                ('amenities', models.TextField()),
                ('room_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dicount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=300)),
                ('floor', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('bed_count', models.IntegerField()),
                ('status', models.CharField(choices=[('V', 'Vacant'), ('R', 'Reserved'), ('P', 'Pending'), ('B', 'Booked')], default='V', max_length=1)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rooms.room_type')),
            ],
        ),
    ]
