# Generated by Django 4.2.10 on 2024-02-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_type',
            old_name='dicount',
            new_name='discount',
        ),
    ]
