# Generated by Django 4.2.10 on 2024-02-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_staff', 'Can view all staff details'), ('change_delete_staff', 'Can change or delete staff details'), ('view_own_details', 'Can view own details')]},
        ),
    ]
