# Generated by Django 4.2.10 on 2024-02-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
