# Generated by Django 4.2.10 on 2024-02-28 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('canceled', 'Cancled')], default='inactive', max_length=20)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.room')),
            ],
        ),
    ]
